#include "os/kernel/arch/exception_frame.hpp"

namespace os::kernel {

namespace {

constexpr uint64_t OS_KERNEL_EXCEPTION_VECTOR_DOUBLE_FAULT = 8ULL;
constexpr uint64_t OS_KERNEL_EXCEPTION_VECTOR_INVALID_TSS = 10ULL;
constexpr uint64_t OS_KERNEL_EXCEPTION_VECTOR_SEGMENT_NOT_PRESENT = 11ULL;
constexpr uint64_t OS_KERNEL_EXCEPTION_VECTOR_STACK_SEGMENT_FAULT = 12ULL;
constexpr uint64_t OS_KERNEL_EXCEPTION_VECTOR_GENERAL_PROTECTION = 13ULL;
constexpr uint64_t OS_KERNEL_EXCEPTION_VECTOR_PAGE_FAULT = 14ULL;
constexpr uint64_t OS_KERNEL_EXCEPTION_VECTOR_ALIGNMENT_CHECK = 17ULL;
constexpr uint64_t OS_KERNEL_EXCEPTION_VECTOR_CONTROL_PROTECTION = 21ULL;
constexpr uint64_t OS_KERNEL_EXCEPTION_VECTOR_VMM_COMMUNICATION = 29ULL;
constexpr uint64_t OS_KERNEL_EXCEPTION_VECTOR_SECURITY = 30ULL;
constexpr uint64_t OS_KERNEL_EXCEPTION_VECTOR_BREAKPOINT = 3ULL;
constexpr uint64_t OS_KERNEL_EXCEPTION_REQUESTED_PRIVILEGE_LEVEL_MASK = 0x03ULL;
constexpr uint64_t OS_KERNEL_EXCEPTION_USER_PRIVILEGE_LEVEL = 0x03ULL;

}

bool ExceptionPushesHardwareErrorCode(const uint64_t vector) noexcept {
    switch (vector) {
    case OS_KERNEL_EXCEPTION_VECTOR_DOUBLE_FAULT:
    case OS_KERNEL_EXCEPTION_VECTOR_INVALID_TSS:
    case OS_KERNEL_EXCEPTION_VECTOR_SEGMENT_NOT_PRESENT:
    case OS_KERNEL_EXCEPTION_VECTOR_STACK_SEGMENT_FAULT:
    case OS_KERNEL_EXCEPTION_VECTOR_GENERAL_PROTECTION:
    case OS_KERNEL_EXCEPTION_VECTOR_PAGE_FAULT:
    case OS_KERNEL_EXCEPTION_VECTOR_ALIGNMENT_CHECK:
    case OS_KERNEL_EXCEPTION_VECTOR_CONTROL_PROTECTION:
    case OS_KERNEL_EXCEPTION_VECTOR_VMM_COMMUNICATION:
    case OS_KERNEL_EXCEPTION_VECTOR_SECURITY:
        return true;
    default:
        return false;
    }
}

bool IsResumableKernelException(const uint64_t vector) noexcept {
    return vector == OS_KERNEL_EXCEPTION_VECTOR_BREAKPOINT;
}

bool FrameOriginatedFromUser(const ExceptionFrame &frame) noexcept {
    return (frame.code_segment & OS_KERNEL_EXCEPTION_REQUESTED_PRIVILEGE_LEVEL_MASK) ==
           OS_KERNEL_EXCEPTION_USER_PRIVILEGE_LEVEL;
}

}
