"""启动期物理内存与磁盘分区边界的宿主侧唯一规格。"""


OS_BOOT_LAYOUT_SECTOR_SIZE_BYTES = 512
OS_BOOT_LAYOUT_LBA28_MAXIMUM = 0x0FFF_FFFF
OS_BOOT_LAYOUT_REFERENCE_DISK_SECTOR_COUNT = OS_BOOT_LAYOUT_LBA28_MAXIMUM + 1
OS_BOOT_LAYOUT_REFERENCE_DISK_SIZE_BYTES = (
    OS_BOOT_LAYOUT_REFERENCE_DISK_SECTOR_COUNT
    * OS_BOOT_LAYOUT_SECTOR_SIZE_BYTES
)
OS_BOOT_LAYOUT_KERNEL_STAGING_ADDRESS = 0x0360_0000
OS_BOOT_LAYOUT_KERNEL_STAGING_END_ADDRESS = 0x03E0_0000
OS_BOOT_LAYOUT_KERNEL_STAGING_CAPACITY_BYTES = (
    OS_BOOT_LAYOUT_KERNEL_STAGING_END_ADDRESS
    - OS_BOOT_LAYOUT_KERNEL_STAGING_ADDRESS
)
OS_BOOT_LAYOUT_KERNEL_MAXIMUM_LOAD_END_ADDRESS = (
    OS_BOOT_LAYOUT_KERNEL_STAGING_ADDRESS
)
OS_BOOT_LAYOUT_ROOTFS_START_LBA = 32_768
OS_BOOT_LAYOUT_ROOTFS_START_BYTES = (
    OS_BOOT_LAYOUT_ROOTFS_START_LBA
    * OS_BOOT_LAYOUT_SECTOR_SIZE_BYTES
)
OS_BOOT_LAYOUT_REFERENCE_ROOTFS_AVAILABLE_BYTES = (
    OS_BOOT_LAYOUT_REFERENCE_DISK_SIZE_BYTES
    - OS_BOOT_LAYOUT_ROOTFS_START_BYTES
)
