"""rootfs v4 宿主工具公开入口。

底层实现暂时保留在历史模块名 ``rootfs_v2`` 中，避免破坏旧脚本的导入；本模块
冻结 v2.3 对外使用的格式 4 名称。旧入口只作为兼容别名，不再代表盘面版本。
"""

from .rootfs_v2 import (
    OS_ROOTFS_V2_BLOCK_SIZE_BYTES,
    OS_ROOTFS_V2_CAPACITY_IMAGE_SIZE_BYTES,
    OS_ROOTFS_V2_CORRUPTION_KINDS,
    OS_ROOTFS_V2_DATA_BLOCK_COUNT,
    OS_ROOTFS_V2_DATA_BITMAP_BLOCK_COUNT,
    OS_ROOTFS_V2_DATA_BITMAP_START_RELATIVE_BLOCK,
    OS_ROOTFS_V2_DATA_START_RELATIVE_BLOCK,
    OS_ROOTFS_V2_DIRECTORY_ENTRY_SIZE_BYTES,
    OS_ROOTFS_V2_DIRECT_BLOCK_COUNT,
    OS_ROOTFS_V2_INODE_COUNT,
    OS_ROOTFS_V2_INODE_BITMAP_BLOCK_COUNT,
    OS_ROOTFS_V2_INODE_BITMAP_START_RELATIVE_BLOCK,
    OS_ROOTFS_V2_INODE_SIZE_BYTES,
    OS_ROOTFS_V2_INODE_TABLE_START_RELATIVE_BLOCK,
    OS_ROOTFS_V2_INITIAL_NEXT_INODE_GENERATION,
    OS_ROOTFS_V2_INITIAL_ROOT_GENERATION,
    OS_ROOTFS_V2_JOURNAL_BLOCK_COUNT,
    OS_ROOTFS_V2_JOURNAL_START_RELATIVE_BLOCK,
    OS_ROOTFS_V2_MAXIMUM_FILE_SIZE_BYTES,
    OS_ROOTFS_V2_MINIMUM_DISK_SIZE_BYTES,
    OS_ROOTFS_V2_MODE_DIRECTORY,
    OS_ROOTFS_V2_MODE_REGULAR,
    OS_ROOTFS_V2_NODE_TYPE_DIRECTORY,
    OS_ROOTFS_V2_NODE_TYPE_REGULAR_FILE,
    OS_ROOTFS_V2_NODE_TYPE_SYMBOLIC_LINK,
    OS_ROOTFS_V2_POINTERS_PER_INDIRECT_BLOCK,
    OS_ROOTFS_V2_REGION_SIZE_BYTES,
    OS_ROOTFS_V2_ROOT_INODE_NUMBER,
    OS_ROOTFS_V2_START_LBA,
    OS_ROOTFS_V2_TOTAL_BLOCK_COUNT,
    OS_ROOTFS_V2_VERSION,
    RootfsV2DirectoryEntry,
    RootfsV2Inode,
    RootfsV2Inspection,
    RootfsV2InstallFile,
    RootfsV2Reader,
    RootfsV2Superblock,
    calculateRootfsV2Crc32,
    corruptRootfsV2,
    decodeRootfsV2DirectoryEntry,
    decodeRootfsV2Inode,
    decodeRootfsV2PointerBlock,
    decodeRootfsV2Superblock,
    encodeRootfsV2DirectoryEntry,
    encodeRootfsV2Inode,
    encodeRootfsV2PointerBlock,
    encodeRootfsV2Superblock,
    formatRootfsV2,
    inspectRootfsV2,
    inspectionAsJson,
    installRootfsV2Files,
    readRootfsV2Block,
    readRootfsV2File,
    rootfsV2AbsoluteOffset,
    validateRootfsV2StaticLayout,
    writeRootfsV2Block,
)


OS_ROOTFS_V4_BLOCK_SIZE_BYTES = OS_ROOTFS_V2_BLOCK_SIZE_BYTES
OS_ROOTFS_V4_CAPACITY_IMAGE_SIZE_BYTES = (
    OS_ROOTFS_V2_CAPACITY_IMAGE_SIZE_BYTES
)
OS_ROOTFS_V4_CORRUPTION_KINDS = OS_ROOTFS_V2_CORRUPTION_KINDS
OS_ROOTFS_V4_DATA_BLOCK_COUNT = OS_ROOTFS_V2_DATA_BLOCK_COUNT
OS_ROOTFS_V4_DATA_BITMAP_BLOCK_COUNT = OS_ROOTFS_V2_DATA_BITMAP_BLOCK_COUNT
OS_ROOTFS_V4_DATA_BITMAP_START_RELATIVE_BLOCK = (
    OS_ROOTFS_V2_DATA_BITMAP_START_RELATIVE_BLOCK
)
OS_ROOTFS_V4_DATA_START_RELATIVE_BLOCK = (
    OS_ROOTFS_V2_DATA_START_RELATIVE_BLOCK
)
OS_ROOTFS_V4_DIRECT_BLOCK_COUNT = OS_ROOTFS_V2_DIRECT_BLOCK_COUNT
OS_ROOTFS_V4_DIRECTORY_ENTRY_SIZE_BYTES = (
    OS_ROOTFS_V2_DIRECTORY_ENTRY_SIZE_BYTES
)
OS_ROOTFS_V4_FORMAT_VERSION = OS_ROOTFS_V2_VERSION
OS_ROOTFS_V4_MODE_DIRECTORY = OS_ROOTFS_V2_MODE_DIRECTORY
OS_ROOTFS_V4_MODE_REGULAR = OS_ROOTFS_V2_MODE_REGULAR
OS_ROOTFS_V4_INODE_COUNT = OS_ROOTFS_V2_INODE_COUNT
OS_ROOTFS_V4_INODE_BITMAP_BLOCK_COUNT = OS_ROOTFS_V2_INODE_BITMAP_BLOCK_COUNT
OS_ROOTFS_V4_INODE_BITMAP_START_RELATIVE_BLOCK = (
    OS_ROOTFS_V2_INODE_BITMAP_START_RELATIVE_BLOCK
)
OS_ROOTFS_V4_INODE_SIZE_BYTES = OS_ROOTFS_V2_INODE_SIZE_BYTES
OS_ROOTFS_V4_INODE_TABLE_START_RELATIVE_BLOCK = (
    OS_ROOTFS_V2_INODE_TABLE_START_RELATIVE_BLOCK
)
OS_ROOTFS_V4_INITIAL_NEXT_INODE_GENERATION = (
    OS_ROOTFS_V2_INITIAL_NEXT_INODE_GENERATION
)
OS_ROOTFS_V4_INITIAL_ROOT_GENERATION = OS_ROOTFS_V2_INITIAL_ROOT_GENERATION
OS_ROOTFS_V4_JOURNAL_BLOCK_COUNT = OS_ROOTFS_V2_JOURNAL_BLOCK_COUNT
OS_ROOTFS_V4_JOURNAL_START_RELATIVE_BLOCK = (
    OS_ROOTFS_V2_JOURNAL_START_RELATIVE_BLOCK
)
OS_ROOTFS_V4_MAXIMUM_FILE_SIZE_BYTES = (
    OS_ROOTFS_V2_MAXIMUM_FILE_SIZE_BYTES
)
OS_ROOTFS_V4_MINIMUM_DISK_SIZE_BYTES = OS_ROOTFS_V2_MINIMUM_DISK_SIZE_BYTES
OS_ROOTFS_V4_NODE_TYPE_DIRECTORY = OS_ROOTFS_V2_NODE_TYPE_DIRECTORY
OS_ROOTFS_V4_NODE_TYPE_REGULAR_FILE = OS_ROOTFS_V2_NODE_TYPE_REGULAR_FILE
OS_ROOTFS_V4_NODE_TYPE_SYMBOLIC_LINK = OS_ROOTFS_V2_NODE_TYPE_SYMBOLIC_LINK
OS_ROOTFS_V4_POINTERS_PER_INDIRECT_BLOCK = (
    OS_ROOTFS_V2_POINTERS_PER_INDIRECT_BLOCK
)
OS_ROOTFS_V4_REGION_SIZE_BYTES = OS_ROOTFS_V2_REGION_SIZE_BYTES
OS_ROOTFS_V4_ROOT_INODE_NUMBER = OS_ROOTFS_V2_ROOT_INODE_NUMBER
OS_ROOTFS_V4_START_LBA = OS_ROOTFS_V2_START_LBA
OS_ROOTFS_V4_TOTAL_BLOCK_COUNT = OS_ROOTFS_V2_TOTAL_BLOCK_COUNT

RootfsV4DirectoryEntry = RootfsV2DirectoryEntry
RootfsV4Inode = RootfsV2Inode
RootfsV4Inspection = RootfsV2Inspection
RootfsV4InstallFile = RootfsV2InstallFile
RootfsV4Reader = RootfsV2Reader
RootfsV4Superblock = RootfsV2Superblock

calculateRootfsV4Crc32 = calculateRootfsV2Crc32
corruptRootfsV4 = corruptRootfsV2
decodeRootfsV4DirectoryEntry = decodeRootfsV2DirectoryEntry
decodeRootfsV4Inode = decodeRootfsV2Inode
decodeRootfsV4PointerBlock = decodeRootfsV2PointerBlock
decodeRootfsV4Superblock = decodeRootfsV2Superblock
encodeRootfsV4DirectoryEntry = encodeRootfsV2DirectoryEntry
encodeRootfsV4Inode = encodeRootfsV2Inode
encodeRootfsV4PointerBlock = encodeRootfsV2PointerBlock
encodeRootfsV4Superblock = encodeRootfsV2Superblock
formatRootfsV4 = formatRootfsV2
inspectRootfsV4 = inspectRootfsV2
installRootfsV4Files = installRootfsV2Files
readRootfsV4Block = readRootfsV2Block
readRootfsV4File = readRootfsV2File
rootfsV4AbsoluteOffset = rootfsV2AbsoluteOffset
validateRootfsV4StaticLayout = validateRootfsV2StaticLayout
writeRootfsV4Block = writeRootfsV2Block
